const SectionActionType = {
    FETCH_SECTION_DATA_START:'FETCH_SECTION_DATA_START',
    FETCH_SECTION_DATA_SUCCESS:'FETCH_SECTION_DATA_SUCCESS',
    FETCH_SECTION_DATA_FAILED:'FETCH_SECTION_DATA_FAILED',
    SET_SECTION:'SET_SECTION',
    SET_PERCENT:'SET_PERCENT'
};

export default SectionActionType;